name = "RationalProjectivePlane"
uuid = "c6f45eda-53e9-4846-927e-3bf2d3f4e2f3"
authors = ["Ed Scheinerman <ers@jhu.edu>"]
version = "0.1.0"

[deps]
AbstractLattices = "398f06c4-4d28-53ec-89ca-5b2656b7603d"
LinearAlgebraX = "9b3f67b0-2d00-526e-9884-9e4938f8fb88"

[compat]
LinearAlgebraX = "0.1"
AbstractLattices = "0.3"
julia = "1"
